### ISSUE TITLE
USB Power Properties issues with devices like iPhone XS

### ISSUE THREAD

**Issue by Sniki** [Snikii/Lenovo-Thinkpad-T440S#1]
There is a Power Properties issue with some USB Ports where if you connect a device like iPhone XS the device will go into a "Connected then Disconnected/Charging, Not Charging" loop as reported by @joshuaseltzer and confirmed by me on my Lenovo ThinkPad X240.

To-Do:

- [x] Test by creating a USBPorts.kext with Hackintool instead of USBInjectAll.kext + SSDT

- [x] Test by overriding SMBIOS Power Properties with config.plist /Devices/Properties or by injecting them on the SSDT-USB

- [x] Test natively without SSDT-USB and without USBInjectAll.kext

- [x] Find the source of the problem and apply a fix for the issue

**Comment by joshuaseltzer** [comment]
@Sniki as always, thanks for your support in this machine.

I’d happily test any potential solutions or bug fixes. Just comment on this issue and I’ll see it!

**Comment by Sniki** [comment]
> @Sniki as always, thanks for your support in this machine.
> 
> I’d happily test any potential solutions or bug fixes. Just comment on this issue and I’ll see it!

I think i solved the problem, will do a few more test , a few more reboots, a few more scenarios on cold boot and after wake from sleep just to make sure it's 100% fixed and will provide the fix

**Comment by joshuaseltzer** [comment]
Wow - this is fantastic if true.  I'm very curious as to how you did it, since I had tried everything I could think of without any sort of success.  I look forward to the updates.

**Comment by Sniki** [comment]
Solved, files with fixes to be uploaded tonight

**Comment by usman2006** [comment]
hi sniki,
i got still the same with my ipad pro but only on the normal usb port on the t440s
if i plug in the "always power on" usb port, it work fine, it even charge the ipad.
on my dock i have also a always power on" usb port and it works fine , also it charge the ipad.
on the others usb port on dock it also work fine but i get msg that it cant be charged (thats normal )
i have the latest  file.

thx
